### ISSUE TITLE
написание кода дизайна программы

### ISSUE THREAD

**Issue by konstatnine32123** [konstatnine32123/konstantine#12]

**Comment by Takunava** [comment]
Каков статус задачи?

**Comment by Takunava** [comment]
Если выполнена, то необходимо это как подтвердить и изменить статус задачи

**Comment by RyjkovAlexey** [comment]
Собрали приложение с 2.5D макетами карт, все работает
![Screenshot_1](https://user-images.githubusercontent.com/61025407/80605602-f79a2780-8a3b-11ea-8c7f-8da8cf7b75fe.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/61025407/80605608-f963eb00-8a3b-11ea-9a3d-9d4a1aaae00f.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/61025407/80605611-fa951800-8a3b-11ea-9c59-fb7ba06324cc.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/61025407/80605618-fc5edb80-8a3b-11ea-8b58-b62a7ddf6d18.jpg)


Ссылка на собранное приложение: https://drive.google.com/file/d/1Ldno2r9b3g4qj-d_Imhe1nbS_qeA-aBw/view?usp=sharing

Нужна еще иконка приложения
